Vagrant.configure("2") do |config|

	config.vm.network "private_network", ip: "192.168.0.20", virtualbox__intnet: "mynetworkB"
  config.vm.box = "debian/buster64"
  config.vm.provision :shell, path: "bootstrap.sh"

  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
  end
end
